"""empty message

Revision ID: aa1f2d485c62
Revises: 931559655c61
Create Date: 2025-05-22 14:37:11.726517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa1f2d485c62'
down_revision: Union[str, None] = '931559655c61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('houses', 'Neighborhood',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('houses', 'SalePrice',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('houses', 'SalePrice',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('houses', 'Neighborhood',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
